routes:
  /about-us/: about-us
  /treatments/: treatments
  /child-wellness/: child-wellness
  /women-wellness/: women-wellness
  /therapies/: therapies
  /team/: team
  /culture/: culture
  /appointment/: appointment

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-hash-internal

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/